### ISSUE TITLE
Dropdown modal opens to the top now instead of to the bottom

### ISSUE THREAD

**Issue by donni106** [siemiatj/react-native-modal-dropdown#1]
There was a pull request which changed the top value of the dropdown modal. I already commented there. Since that change, the dropdown modal opens to the top now instead of to the bottom.
https://github.com/siemiatj/react-native-modal-dropdown-legacy/pull/1

These lines are effected:
https://github.com/siemiatj/react-native-modal-dropdown/blob/9ea6efc570a6ac36f4c625350d8f6edf9dc942ea/components/ModalDropdown.js#L263-L268

I will have a look on the logic and try to find a solution other to reverting the change from the pull request.

**Comment by deniscreamer** [comment]
The same

**Comment by siemiatj** [comment]
Merged. Will test more thoroughly later but looks good so far.

**Comment by QuintonC** [comment]
I'm still experiencing this issue. Was this fix not merged in? It says that it was, but maybe I'm missing something?

**Comment by donni106** [comment]
No, the fix is not merged yet.

**Comment by QuintonC** [comment]
Are there blockers or something? Any way I can help?

**Comment by donni106** [comment]
@siemiatj said, that he is busy at his work and tries his best to keep his hands on here.

**Comment by siemiatj** [comment]
Yeah sorry guys. I'm doing my best and hopefully I can son find some time to fix something by myself. Thanks for the PRs so far !
