### ISSUE TITLE
Why do the installation instructions point to another fork?

### ISSUE THREAD

**Issue by tgearig** [siemiatj/react-native-modal-dropdown#15]
Currently, the readme says to use the follow line to install:

`npm i https://github.com/Kishanjvaghela/react-native-modal-dropdown -save`

Why does it not say:

`npm i https://github.com/siemiatj/react-native-modal-dropdown -save`

It was changed in this commit: a9eba80cf312745c76b90b543b8998cb462a96fd. Has the ownership of this package changed?

**Comment by siemiatj** [comment]
I didn't notice that, when merging a PR. Some dickhead changed that for no reason. Thanks for catching
