### ISSUE TITLE
Could we publish a version v1.0.2 with recent fixes?

### ISSUE THREAD

**Issue by tlapuste** [siemiatj/react-native-modal-dropdown#47]
@siemiatj Could you please `npm publish` a v1.0.2 off master after merging in this change? [https://github.com/siemiatj/react-native-modal-dropdown/pull/46/files](https://github.com/siemiatj/react-native-modal-dropdown/pull/46/files)

This issue in particular has been a show stopper: [Fixed Issue when initialScrollIndex failed #41 ](https://github.com/siemiatj/react-native-modal-dropdown/pull/41)
Causing issues on release builds so have had to ref the master branch instead of npm.

Issues that this fix addresses:
https://github.com/siemiatj/react-native-modal-dropdown/issues/40
https://github.com/siemiatj/react-native-modal-dropdown/issues/38

**Comment by siemiatj** [comment]
Done, thanks for the PR.
